---
info:
  title: Recog
  description: Pattern recognition for hosts, services, and content
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/recog
  x-cortex-tag: recog
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
